_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.4
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 5
                - 41
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.4
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-arm64
NUM_EPOCHS:
    value: 30
batch_norm:
    value: true
batch_size:
    value: 32
conv1_kernel_size:
    value: 3
conv1_out_channels:
    value: 16
conv1_padding:
    value: 1
conv2_kernel_size:
    value: 3
conv2_out_channels:
    value: 32
conv2_padding:
    value: 1
conv3_kernel_size:
    value: 3
conv3_out_channels:
    value: 64
conv3_padding:
    value: 1
dropout_rate:
    value: 0.5
fc1_units:
    value: 128
lr:
    value: 0.001
scheduler:
    value: false
weight_decay:
    value: false
